### PR TITLE
Update files

### PR DESCRIPTION
**Pull request by ghost**
Enter a new functional.

### CODE REVIEW

**Comment by theIYD** [comment]
Thank you for contributing to this project.

Before merging the pull request, could you post a demo of the working app showing your changes for confirmation ? 

Thanks

**Comment by Den1997** [comment]
Here is a link to the gif - [https://vk.com/doc17861045_484262376?hash=b45c1902e136c71597&dl=061c343f5903222fb6](url)
Don't forget to download the necessary libraries for everything to work.

**Comment by Den1997** [comment]
Here is a link to the gif - [https://ru.files.fm/u/j7chgwgm](url)
Don't forget to download the necessary libraries for everything to work.

**Comment by Den1997** [comment]
Here is a link to the gif - https://transfiles.ru/9lbpr
Don't forget to download the necessary libraries for everything to work.

**Pull request merged**
